const GET_TASKS = 'GET_TASKS',
    CREATE_TASK = 'CREATE_TASK',
    UPDATE_TASK = 'UPDATE_TASK',
    DELETE_TASK = 'DELETE_TASK',
    TOGGLE_LOADING = 'TOGGLE_LOADING';

export {
    GET_TASKS,
    CREATE_TASK,
    UPDATE_TASK,
    DELETE_TASK,
    TOGGLE_LOADING
}
